# Generated by Django 3.0.3 on 2020-02-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryForm',
        ),
        migrations.DeleteModel(
            name='SafeKeepingForm',
        ),
        migrations.DeleteModel(
            name='WareHousingForm',
        ),
    ]
